data_sources:
  prescriptions:
    enabled: true
    file_path: "data/raw/alternative/mmi_MedicatieVoorschrift.csv"
    columns:
      required:
        patient_id:             "mrn"
        patient_contact_id:     "encounter_id"
        start_datetime:         "medication_start"
        stop_datetime:          "medication_stop"
        prescription_datetime:  "order_timestamp"
        medication_name:        "generic_name"
      optional:
        administration_route:   "admin_route"
        specialty:              "ordering_dept"

  order_specifications:
    enabled: false
    file_path: "data/raw/alternative/OrderSpecificatievraagAntwoord.csv"
    columns:
      required: {}
      optional: {}

  cultures:
    enabled: true
    file_path: "data/raw/alternative/kweken.csv"
    columns:
      required:
        patient_id:             "mrn"
        sample_datetime:        "specimen_datetime"
        material_category:      "source"
      optional:
        culture_result:         "culture_finding"

  admissions:
    enabled: false
    file_path: "data/raw/alternative/mmi_OpnameDeeltraject.csv"
    columns:
      required: {}
      optional: {}

analysis_options:
  culture_time_windows:
    default:
      hours_before: 72
      hours_after:  24
    intra_abdominal:
      hours_before: 72
      hours_after:  48

output:
  format: "json"
  file_path: "data/processed/alternative/output.json"
