data_sources:
  prescriptions:
    enabled: true
    file_path: "data/raw/extended/mmi_MedicatieVoorschrift.csv"
    columns:
      patient_id: "Pseudo_id"
      patient_contact_id: "PatientContactId"
      start_datetime: "StartDatumTijd"
      stop_datetime: "StopDatumTijd"
      prescription_datetime: "VoorschrijfDatumTijd"
      medication_name: "MedicatieStofnaam"
      administration_route: "ToedieningsRoute"
      specialty: "SpecialismeOmschrijving"
      # Additional columns for extended scenario
      subspecialty: "SubSpecialismeOmschrijving"
      department: "WerkplekOmschrijving"
      dosage_min: "DoseringBerekendMin"
      dosage_max: "DoseringBerekendMax"
      dosage_unit: "DoseringBerekendEenheidOmschrijving"
      frequency: "MedicatieFrequentieOmschrijving"
      status: "OrderStatus"

  order_specifications:
    enabled: true
    file_path: "data/raw/extended/OrderSpecificatievraagAntwoord.csv"
    columns:
      patient_id: "Pseudo_id"
      patient_contact_id: "PatientContactId"
      order_id: "OrderId"
      question_id: "OrderSpecificatievraagId"
      answer: "OrderSpecificatievraagAntwoord"
      # Additional columns
      question_text: "OrderSpecificatievraagFormulering"
      location: "ZiekenhuisLocatie"
      is_executable: "IsZorgOrderUitvoerbaar"
      is_parent: "IsZorgOrderParent"

  cultures:
    enabled: true
    file_path: "data/raw/extended/kweken.csv"
    columns:
      patient_id: "Pseudo_id"
      sample_datetime: "afnamedatumtijd"
      material_category: "materiaal_catCustom"
      culture_result: "kweek_uitslagDef"
      # Additional columns
      material_code: "materiaal_code"
      material_description: "materiaal_description"
      culture_purpose: "kweekdoel"
      department: "afdeling"
      location: "AUMC_locatie"

  admissions:
    enabled: true
    file_path: "data/raw/extended/mmi_OpnameDeeltraject.csv"
    columns:
      patient_id: "Pseudo_id"
      patient_contact_id: "PatientContactId"
      admission_start: "OpnametrajectOpnameDatumTijd"
      admission_end: "OpnametrajectOntslagDatumTijd"
      # Additional columns
      is_emergency: "IsSEHDeeltraject"
      is_icu: "IsICDeeltraject"
      specialty: "Specialisme"
      subspecialty: "Subspecialisme"
      department: "Werkplek"
      duration_hours: "LigduurUren"

analysis_options:
  culture_time_windows:
    default:
      hours_before: 72
      hours_after: 24
    intra_abdominal:
      hours_before: 72
      hours_after: 48
    emergency:  # Additional time window for emergency cases
      hours_before: 24
      hours_after: 12
    icu:  # Additional time window for ICU cases
      hours_before: 48
      hours_after: 36

output:
  format: "json"
  file_path: "data/processed/extended/output.json" 